name: Run psuedocode on ubuntu

on:
  workflow_dispatch:
    inputs:
      comp:
        description: 'Component to run'
        required: true
        default: 'comp1'
        type: choice
        options:
          - comp1
          - comp2
          - comp4
env:
      JMETER_THREADS: 10
      JMETER_DURATION: 60
      JMETER_PATH: './sample.jmx'
jobs:
  performance_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '16'
          distribution: 'temurin'
          architecture: x64
 
      - name: Checkout code
        uses: actions/checkout@v4
      - name: setup python and aws cli
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli
          sudo apt-get install -y jq python3 python3-pip
          pip install -r requirements.txt
 
      - name: Install jq
        run: sudo apt install -y jq
 
      - name: Setup-Jmeter
        run: |
          sudo apt-get update
          sudo apt install curl -y
          sudo apt install -y default-jdk
          sudo curl -O https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.5.tgz
          sudo tar -xvf apache-jmeter-5.5.tgz
          cd $GITHUB_WORKSPACE/apache-jmeter-5.5/lib && sudo curl -O https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.2.1/cmdrunner-2.2.1.jar
          cd $GITHUB_WORKSPACE/apache-jmeter-5.5/lib/ext && sudo curl -O https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.6/jmeter-plugins-manager-1.6.jar
          cd $GITHUB_WORKSPACE/apache-jmeter-5.5/lib && sudo java -jar cmdrunner-2.2.1.jar --tool org.jmeterplugins.repository.PluginManagerCMD install jpgc-synthesis,jpgc-graphs-basic,jpgc-graphs-additional,jpgc-cmd,jpgc-graphs-dist,jpgc-standard,jpgc-casutg
      - name: Install PerfMon Plugin
        run: |
          cd $GITHUB_WORKSPACE/apache-jmeter-5.5/lib
          sudo java -jar cmdrunner-2.2.1.jar --tool org.jmeterplugins.repository.PluginManagerCMD install jpgc-perfmon

      - name: Running JMeter for Jmeter-API-script-1
        run: |
          comp=${{ github.event.inputs.comp }}
          echo "Component selected: $comp"
          in_section=false
          while IFS= read -r line; do
            if [[ $line == "$comp:" ]]; then
              in_section=true
              continue
            elif [[ $line == *:* ]]; then
              in_section=false
            fi
  
            if $in_section; then
              echo "Running script: $line"
              $GITHUB_WORKSPACE/apache-jmeter-5.5/bin/./jmeter.sh -n -t $line
              echo "Running JMeter HTML"
              $GITHUB_WORKSPACE/apache-jmeter-5.5/bin/./jmeter.sh -Jjmeter.reportgenerator.exporter.html.series_filter="((T[0-9] {1,3}_))" -g DeterAPI/SampleAPIjtl1.jtl -o DeterAPI/HTMLReport1
            fi
          done < scripts_to_run.txt
